VMMonitor/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from monitor.views import Index
from apps.servers.views import ServerCreate, ServerUpdate, ServerDelete, ServerList, ServerDetail
from apps.scripts.views import ScriptList, ScriptDetail, ScriptCreate, ScriptUpdate, ScriptDelete
from apps.users.views import UserList, UserDetail, UserCreate, UserUpdate, UserDelete
from apps.alerts.views import AlertList, AlertDetail, AlertCreate, AlertUpdate, AlertDelete
from apps.scripts.api import ScriptResource
from apps.scripts.api import ScriptRun
from apps.servers.api import ServerResource
from apps.users.api import ServerUserResources
from apps.statistics.api import StatisticResource
from apps.statistics.api import SpecificStatisticResource

admin.autodiscover()

script_resource = ScriptResource()
run_resource = ScriptRun()
server_resource = ServerResource()
user_resource = ServerUserResources()
statistic_resource = StatisticResource()
specific_statistic_resource = SpecificStatisticResource()

urlpatterns = patterns('',
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^search/$', 'apps.books.views.search'),
                       url(r'^$', Index.as_view(), name='index'),

                       url(r'^server-detail/(?P<pk>\d+)/$', ServerDetail.as_view(), name='server-detail'),
                       url(r'^server-create/$', ServerCreate.as_view(), name='server-create'),
                       url(r'^server-update/(?P<pk>\d+)/$', ServerUpdate.as_view(), name='server-update'),
                       url(r'^server-delete/(?P<pk>\d+)/$', ServerDelete.as_view(), name='server-delete'),
                       url(r'^server-list/$', ServerList.as_view(), name='server-list'),

                       url(r'^alert-detail/(?P<pk>\d+)/$', AlertDetail.as_view(), name='alert-detail'),
                       url(r'^alert-create/$', AlertCreate.as_view(), name='alert-create'),
                       url(r'^alert-update/(?P<pk>\d+)/$', AlertUpdate.as_view(), name='alert-update'),
                       url(r'^alert-delete/(?P<pk>\d+)/$', AlertDelete.as_view(), name='alert-delete'),
                       url(r'^alert-list/$', AlertList.as_view(), name='alert-list'),

                       url(r'^script-detail/(?P<pk>\d+)/$', ScriptDetail.as_view(), name='script-detail'),
                       url(r'^script-create/$', ScriptCreate.as_view(), name='script-create'),
                       url(r'^script-update/(?P<pk>\d+)/$', ScriptUpdate.as_view(), name='script-update'),
                       url(r'^script-delete/(?P<pk>\d+)/$', ScriptDelete.as_view(), name='script-delete'),
                       url(r'^script-list/$', ScriptList.as_view(), name='script-list'),

                       url(r'^user-list/$', UserList.as_view(), name='user-list'),
                       url(r'^user-detail/(?P<pk>\d+)/$', UserDetail.as_view(), name='user-detail'),
                       url(r'^user-create/$', UserCreate.as_view(), name='user-create'),
                       url(r'^user-update/(?P<pk>\d+)/$', UserUpdate.as_view(), name='user-update'),
                       url(r'^user-delete/(?P<pk>\d+)/$', UserDelete.as_view(), name='user-delete'),

                       url(r'api/', include(script_resource.urls)),
                       url(r'api/', include(run_resource.urls)),
                       url(r'api/', include(server_resource.urls)),
                       url(r'api/', include(user_resource.urls)),
                       url(r'api/', include(statistic_resource.urls)),
                       url(r'api/', include(specific_statistic_resource.urls)),

                       url(r'', include('gcm.urls')),
                       url("", include('django_socketio.urls')),
                       url(r'^socket/$', 'apps.sockets.views.connect', name='socket'),
)

apps/alerts/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.forms import ModelForm
from apps.servers.models import Server


class Alert(models.Model):
    EQUALITY_CHOICES = (
        ('S', 'Smaller than <'),
        ('E', 'Equals to =='),
        ('G', 'Greater than >'),
    )
    name = models.CharField(max_length=100)
    command = models.CharField(max_length=255)
    equality = models.CharField(max_length=1, choices=EQUALITY_CHOICES)
    threshold = models.IntegerField()
    time = models.IntegerField()
    message = models.CharField(max_length=150)
    servers = models.ManyToManyField(Server)

    def get_absolute_url(self):
        return reverse('alert-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name


class AlertFrom(ModelForm):
    class Meta:
        model = Alert

apps/books/models.py
from django.db import models
from django.contrib import admin
import os


class Publisher(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=60)
    state_province = models.CharField(max_length=30)
    country = models.CharField(max_length=50)
    website = models.URLField()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]


class Author(models.Model):
    salutation = models.CharField(max_length=10)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=40)
    email = models.EmailField()
    headshot = models.ImageField(upload_to= os.path.join(os.path.dirname(__file__), 'tmp').replace('\\', '/'))

    def __str__(self):
        return '%s %s' % (self.first_name, self.last_name)


class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField(Author)
    publisher = models.ForeignKey(Publisher)
    publication_date = models.DateField()
    num_pages = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return self.title


class BookAdmin(admin.ModelAdmin):
    list_display = ('title', 'publisher', 'publication_date')
    list_filter = ('publisher', 'publication_date')
    ordering = ('-publication_date',)
    search_fields = ('title',)

apps/scripts/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.forms import ModelForm

from apps.servers.models import Server


class Script(models.Model):
    name = models.CharField(max_length=100)
    file = models.FileField(upload_to='.')
    description = models.TextField()
    servers = models.ManyToManyField(Server)

    def get_absolute_url(self):
        return reverse('script-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name


class ScriptFrom(ModelForm):
    class Meta:
        model = Script


class ScriptRun(models.Model):
    script_id = models.CharField(max_length=10)
    server_id = models.CharField(max_length=10)
    status = models.TextField()


class ScriptRunForm(ModelForm):
    class Meta:
        model = ScriptRun

apps/sockets/models.py
from django.db import models

apps/users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django import forms
from apps.users.models import ServerUser


class ServerUserCreationForm(UserCreationForm):
    description = forms.CharField(max_length=100)

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2', 'email', 'description']

    def save(self, commit=True):
        if not commit:
            raise NotImplementedError("Can't create SeverUser and UserProfile without database save")
        user = super(ServerUserCreationForm, self).save(commit=True)
        server_user = ServerUser(user=user, description=self.cleaned_data['description'])
        server_user.save()
        return user, server_user


class ServerUserChangeForm(UserChangeForm):
    description = forms.CharField(max_length=100)

    class Meta:
        model = User
        fields = ['username', 'email', 'description']
        exclude = ['password']

    def __init__(self, *args, **kwargs):
        super(ServerUserChangeForm.user, self).__init__(*args, **kwargs)
        if self.instance and self.instance.pk:
            self.fields['username'] = self.instance.user.username
            self.fields['email'] = self.instance.user.email
            self.fields['description'] = self.instance.description

apps/sockets/views.py
from django.shortcuts import render
from django_socketio import broadcast, broadcast_channel, NoSocket


def connect(request):
    print "connection request"
    template = 'socket.html'
    context = {"output": 'it worked??'}
    if request.method == "POST":
        print request.POST["message"]
        context = {"output": 'it works !!!'}
        connecttion = request.POST["connect"]
        data = {"action": "system", "message": "message"}
        try:
            broadcast_channel(data, channel="connect")
        except NoSocket, e:
            context["message"] = e
        else:
            context["message"] = "Message sent"
    return render(request, template, context)

VMMonitor/templates/alert_delete.html
{% extends "template_base.html" %}

{% block title %}Delete Script{% endblock %}

{% block content %}

{% endblock %}

VMMonitor/templates/alert_detail.html
{% extends "template_base.html" %}

{% block title %}Script detail{% endblock %}

{% block content %}

{% endblock %}

VMMonitor/templates/alert_list.html
{% extends "template_base.html" %}

{% block title %}Alert List{% endblock %}

{% block content %}
<a href={% url "alert-create" %}>Create new alert</a>
{% if object_list %}
    <table class="pure-table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Command</th>
            <th>Equality</th>
            <th>Threshold</th>
            <th>Time</th>
            <th>Message</th>
            <th>Servers</th>
            <th>Details</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    </thead>

    <tbody>
        {% for alert in object_list %}
        <tr>
            <td>{{ alert.id }}</td>
            <td>{{ alert.name }}</td>
            <td>{{ alert.command }}</td>
            <td>{{ alert.equality }}</td>
            <td>{{ alert.threshold }}</td>
            <td>{{ alert.time }}</td>
            <td>{{ alert.message }}</td>
            <td>
            {% if alert.servers %}
                {% for server in script.servers.all %}
                    {{ server }},
                {% endfor %}
            {% endif %}
            </td>
            <td><a href={% url "alert-detail" alert.id %}>Details</a></td>
            <td><a href={% url "alert-update" alert.id %}>Edit</a> </td>
            <td><a href={% url "alert-delete" alert.id %}>Delete</a> </td>
        </tr>
    {% endfor %}
    </tbody>
    </table>
{% else %}
    <p>No alerts listed</p>
{% endif %}
{% endblock %}

VMMonitor/templates/alert_update.html
{% extends "template_base.html" %}

{% block title %}Script detail{% endblock %}

{% block content %}


{% endblock %}

VMMonitor/templates/script_detail.html
{% extends "template_base.html" %}

{% block title %}Script detail{% endblock %}

{% block content %}

<div class="pure-form pure-form-aligned" >
    <div class="pure-controls">
        <legend>Script details</legend>
    </div>
    <div class="pure-control-group">
        <label for="id_id">ID:</label>
        {{ script.id }}
    </div>
    <div class="pure-control-group">
        <label for="id_name">Name:</label>
        {{ script.name }}
    </div>
    <div class="pure-control-group">
        <label for="id_file">File:</label>
        {{ script.file }}
    </div>
    <div class="pure-control-group">
        <label for="id_description">Description:</label>
        {{ script.description }}
    </div>
    <div class="pure-control-group">
        <label for="id_server">Servers:</label>
        {% for server in script.servers.all %}
            {{ server.ip }},
        {% endfor %}
    </div>
    <div class="pure-controls">
        <a href="{% url "script-list" %}">back to script list</a>
        <a href="{% url "index" %}">Back to index</a>
    </div>
</div>
{% endblock %}

VMMonitor/templates/script_list.html
{% extends "template_base.html" %}

{% block title %}Script detail{% endblock %}

{% block content %}
<a href={% url "script-create" %}>Create new script</a>
{% if object_list %}
    <table class="pure-table">
    <thead>
        <tr>
            <th>id</th>
            <th>name</th>
            <th>file</th>
            <th>description</th>
            <th>servers</th>
            <th>Execute</th>
            <th>Details</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    </thead>

    <tbody>
        {% for script in object_list %}
        <tr>
            <td>{{ script.id }}</td>
            <td>{{ script.name }}</td>
            <td>{{ script.file }}</td>
            <td>{{ script.description }}</td>
            <td>
            {% if script.servers %}
                {% for server in script.servers.all %}
                    {{ server }},
                {% endfor %}
            {% endif %}
            </td>
            <td><a href="#">Run</a></td>
            <td><a href={% url "script-detail" script.id %}>Details</a></td>
            <td><a href={% url "script-update" script.id %}>Edit</a> </td>
            <td><a href={% url "script-delete" script.id %}>Delete</a> </td>
        </tr>
    {% endfor %}
    </tbody>
    </table>
{% else %}
    <p>No scripts listed</p>
{% endif %}
{% endblock %}

VMMonitor/templates/script_update.html
{% extends "template_base.html" %}

{% block title %}Script detail{% endblock %}

{% block content %}
<form method="POST" class="pure-form pure-form-aligned" enctype="multipart/form-data">
    <fieldset>
        <div class="pure-controls">
            <legend>Update script</legend>
        </div>
        {{ form.non_field_errors }}
        {% csrf_token %}
        <div class="pure-control-group">
            {{ form.name.errors }}
            <label for="id_name">Name:</label>
            {{ form.name }}
        </div>
        <div class="pure-control-group">
            {{ form.file.errors }}
            <label for="id_file">File:</label>
            {{ form.file }}
        </div>
        <div class="pure-control-group">
            {{ form.description.errors }}
            <label for="id_description">Description:</label>
            {{ form.description }}
        </div>
        <div class="pure-control-group">
            {{ form.servers.errors }}
            <label for="id_servers">Servers:</label>
            {{ form.servers }}
            <span class="helptext"> Hold down "Control", or "Command" on a Mac, to select more than one.</span>
        </div>
        <div class="pure-controls">
            <input type="submit" value="Update" class="pure-button pure-button-primary"/>
            <a href="{% url "script-list" %}">back to script list</a>
            <a href="{% url "index" %}">Back to index</a>
        </div>
    </fieldset>
</form>

{% endblock %}

VMMonitor/templates/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Search {%  if query %} Results {% endif %}</title>
</head>
<body>
<h1>Search</h1>
<form action="." method="get">
    <label for="q">Search</label>
    <input type="text" name="q" value="{{ query|escape }}">
    <input type="submit" value="Search">
</form>
{% if query %}
<h2>Results for "{{ query|escape }}":</h2>
    {% if results %}
    <ul>
        {% for book in results %}
        <li>{{ book }}</li>
        {% endfor %}
    </ul>
    {% else %}
        <p> No books found</p>
    {% endif %}
{% endif %}
</body>
</html>

VMMonitor/templates/server_create_form.html
{% extends "template_base.html" %}

{% block title %}Create new Server{% endblock %}

{% block content %}
<form action="{% url "server-create" %}" method="POST" class="pure-form pure-form-aligned" enctype="multipart/form-data">
    {% csrf_token %}
    <fieldset>
        <div class="pure-controls">
            <legend>Add new server</legend>
        </div>
        {{ form.non_field_errors }}
        {% csrf_token %}
        <div class="pure-control-group">
            {{ form.ip.errors }}
            <label for="id_ip">Ip:</label>
            {{ form.ip }}
        </div>
        <div class="pure-control-group">
            {{ form.name.errors }}
            <label for="id_name">Name:</label>
            {{ form.name }}
        </div>
        <div class="pure-control-group">
            {{ form.location.errors }}
            <label for="id_description">Location:</label>
            {{ form.location }}
        </div>
        <div class="pure-controls">
            <input type="submit" value="Create" class="pure-button pure-button-primary"/><br />
            <a href="{% url "server-list" %}">Back to server list</a>
            <a href="{% url "index" %}">Back to index</a>
        </div>
    </fieldset>
</form>
{% endblock %}

VMMonitor/templates/server_detail.html
{% extends "template_base.html" %}

{% block title %}Server detail{% endblock %}

{% block content %}
<h1>Server details</h1>
<p>ID: {{ server.id }}</p>
<p>IP: {{ server.ip }}</p>
<p>LOCATION: {{ server.location }}</p>
<p>NAME: {{ server.name }}</p>
<p><a href={% url "server-list" %}>List servers</a> </p>

<div class="pure-form pure-form-aligned" >
    <div class="pure-controls">
        <legend>Server details</legend>
    </div>
    <div class="pure-control-group">
        <label for="id_id">ID:</label>
        {{ server.id }}
    </div>
    <div class="pure-control-group">
        <label for="id_ip">IP:</label>
        {{ server.ip }}
    </div>
    <div class="pure-control-group">
        <label for="id_location">Location:</label>
        {{ server.location }}
    </div>
    <div class="pure-control-group">
        <label for="id_name">Name:</label>
        {{ server.name }}
    </div>
    <div class="pure-controls">
        <a href="{% url "server-list" %}">back to server list</a>
        <a href="{% url "index" %}">back to index</a>
    </div>
</div>
{% endblock %}

VMMonitor/templates/socket.html
<!DOCTYPE html>
<html>
<head>
    {% load socketio_tags %}
    {% socketio %}
    <script>
        var socket = new io.Socket();
        socket.connect();
        socket.on('connect', function() {
            socket.subscribe('socket');
            socket.send({server_id : "1"});
        });
    </script>
</head>
<body>
    <textarea id="txt"></textarea>
    <input type="button" id="send-btn" value="Send"></input>
    <div id="recive"></div>
</body>
</html>

VMMonitor/templates/user_delete.html
{% extends "template_base.html" %}

{% block title %}Script detail{% endblock %}

{% block content %}
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>
{% endblock %}

VMMonitor/templates/user_list.html
{% extends "template_base.html" %}

{% block title %}Script detail{% endblock %}

{% block content %}
<a href={% url "user-create" %}>Create new user</a>
{% if object_list %}
    <table border="1">
        <tr>
            <th>id</th>
            <th>name</th>
            <th>description</th>
            <th>Details</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    {% for serveruser in object_list %}
        <tr>
            <td>{{ serveruser.id }}</td>
            <td>{{ serveruser.user.username }}</td>
            <td>{{ serveruser.description }}</td>
            <td><a href={% url "user-detail" serveruser.id %}>Details</a></td>
            <td><a href={% url "user-delete" serveruser.id %}>Delete</a> </td>
            <td><a href={% url "user-update" serveruser.id %}>Edit</a> </td>
        </tr>
    {% endfor %}
    </table>
{% else %}
    <p>No scripts listed</p>
{% endif %}
{% endblock %}

VMMonitor/templates/user_update.html
{% extends "template_base.html" %}

{% block title %}Script detail{% endblock %}

{% block content %}
<form action="" method="POST">
  {% csrf_token %}
  <ul>
    {{ form.as_ul }}
  </ul>
  <input type="submit" value="Update" />
</form>

<a href="{% url "user-list" %}">back to users</a>
{% endblock %}